import assert from 'node:assert/strict'; import { mkdir, mkdtemp, readFile, symlink, writeFile } from 'node:fs/promises'; import { join } from 'node:path'; import test from 'node:test';
import { fakeHttp } from './fake-http.mjs'; import { collectMavenPublication, mavenCreateOrCompare } from '../src/maven-create-or-compare.mjs';
import { createReleaseFixture } from './fixtures.mjs';
async function stage() { const d = await mkdtemp('/tmp/resourcepacks-task8/maven-'); await writeFile(join(d, 'a.jar'), 'a'); await writeFile(join(d, 'a.pom'), 'p'); return d; }
test('maven permits publish only when every remote file is absent', async t => { const h = await fakeHttp((q,s)=>s.writeHead(404).end()); t.after(h.close); assert.deepEqual(await mavenCreateOrCompare({repositoryUrl:h.url,directory:await stage(),allowLocalhostForTests:true}),{publish:true}); });
test('maven skips only when every remote file is byte identical', async t => { const h = await fakeHttp((q,s)=>s.writeHead(200).end(q.url.endsWith('.jar')?'a':'p')); t.after(h.close); assert.deepEqual(await mavenCreateOrCompare({repositoryUrl:h.url,directory:await stage(),allowLocalhostForTests:true}),{publish:false}); });
test('maven rejects partial remote publication', async t => { const h = await fakeHttp((q,s)=>q.url.endsWith('.jar')?s.writeHead(200).end('a'):s.writeHead(404).end()); t.after(h.close); const directory = await stage(); await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:h.url,directory,allowLocalhostForTests:true}),/partial/); });
test('maven rejects redirects, differing complete publications, and network failures', async t=>{const directory=await stage();const redirect=await fakeHttp((q,s)=>s.writeHead(302,{Location:'https://example.invalid'}).end());t.after(redirect.close);await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:redirect.url,directory,allowLocalhostForTests:true}),/refused redirect/);const different=await fakeHttp((q,s)=>s.writeHead(200).end('wrong'));t.after(different.close);await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:different.url,directory,allowLocalhostForTests:true}),/differs/);await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:'http://127.0.0.1:1',directory,allowLocalhostForTests:true}),/request failed/);});
async function exactStage(){const fixture=await createReleaseFixture();const root=join(fixture.root,'maven');const version=join(root,'gg','grounds','resourcepacks-catalog','0.1.0');await mkdir(version,{recursive:true});const values=new Map([['resourcepacks-catalog-0.1.0.jar',fixture.files.get('grounds-resourcepacks-catalog-0.1.0.jar')],['resourcepacks-catalog-0.1.0-sources.jar',Buffer.from('sources')],['resourcepacks-catalog-0.1.0.pom',Buffer.from('<project/>')],['resourcepacks-catalog-0.1.0.module',Buffer.from('{}')]]);for(const[name,bytes]of values)await writeFile(join(version,name),bytes);return{fixture,root,version,values};}
test('Maven staging is snapshotted as the exact full manifest publication and survives original mutation',async t=>{const staged=await exactStage();const publication=await collectMavenPublication({stagingDirectory:staged.root,manifest:staged.fixture.manifest});t.after(()=>publication.close());assert.equal(publication.files.length,4);assert.ok(publication.snapshotDirectory.startsWith('/tmp/'));await writeFile(join(staged.version,'resourcepacks-catalog-0.1.0.jar'),'mutated');assert.deepEqual(await readFile(publication.files.find(file=>file.path.endsWith('.jar')&&!file.path.includes('-sources')).file),staged.fixture.files.get('grounds-resourcepacks-catalog-0.1.0.jar'));});
test('Maven staging rejects extra, missing, symlink leaf, and symlink ancestor trees',async()=>{const extra=await exactStage();await writeFile(join(extra.version,'other.jar'),'x');await assert.rejects(()=>collectMavenPublication({stagingDirectory:extra.root,manifest:extra.fixture.manifest}),/exact Maven publication/i);const linked=await exactStage();const pom=join(linked.version,'resourcepacks-catalog-0.1.0.pom');const target=`${pom}.target`;await writeFile(target,'x');const{unlink}=await import('node:fs/promises');await unlink(pom);await symlink(target,pom);await assert.rejects(()=>collectMavenPublication({stagingDirectory:linked.root,manifest:linked.fixture.manifest}),/symbolic link|regular/i);const ancestor=await exactStage();const moved=`${ancestor.root}-real`;const{rename}=await import('node:fs/promises');await rename(ancestor.root,moved);await symlink(moved,ancestor.root);await assert.rejects(()=>collectMavenPublication({stagingDirectory:ancestor.root,manifest:ancestor.fixture.manifest}),/symbolic link/i);});
test('Maven comparison rejects attacker repository origin before sending authorization',async()=>{const directory=await stage();let calls=0;await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:'https://attacker.example',directory,username:'actor',token:'TOKEN_MARKER',fetchImpl:async()=>{calls+=1;return new Response('',{status:404});}}),/repository URL is not trusted/);assert.equal(calls,0);});
test('Maven comparison times out pending headers and stalled response bodies',async()=>{const directory=await stage();for(const fetchImpl of [()=>new Promise(()=>{}),async()=>new Response(new ReadableStream({start(){}}),{status:200})]){const operation=mavenCreateOrCompare({repositoryUrl:'http://127.0.0.1:1',directory,allowLocalhostForTests:true,fetchImpl,timeoutMs:20});assert.equal(await Promise.race([assert.rejects(()=>operation,/Maven request timed out/).then(()=> 'timeout'),new Promise(resolve=>setTimeout(()=>resolve('hung'),200))]),'timeout');}});
