import assert from 'node:assert/strict'; import { mkdir, mkdtemp, symlink, writeFile } from 'node:fs/promises'; import { join } from 'node:path'; import test from 'node:test';
import { fakeHttp } from './fake-http.mjs'; import { collectMavenPublication, mavenCreateOrCompare } from '../src/maven-create-or-compare.mjs';
import { createReleaseFixture } from './fixtures.mjs';
async function stage() { const d = await mkdtemp('/tmp/resourcepacks-task8/maven-'); await writeFile(join(d, 'a.jar'), 'a'); await writeFile(join(d, 'a.pom'), 'p'); return d; }
test('maven permits publish only when every remote file is absent', async t => { const h = await fakeHttp((q,s)=>s.writeHead(404).end()); t.after(h.close); assert.deepEqual(await mavenCreateOrCompare({repositoryUrl:h.url,directory:await stage()}),{publish:true}); });
test('maven skips only when every remote file is byte identical', async t => { const h = await fakeHttp((q,s)=>s.writeHead(200).end(q.url.endsWith('.jar')?'a':'p')); t.after(h.close); assert.deepEqual(await mavenCreateOrCompare({repositoryUrl:h.url,directory:await stage()}),{publish:false}); });
test('maven rejects partial remote publication', async t => { const h = await fakeHttp((q,s)=>q.url.endsWith('.jar')?s.writeHead(200).end('a'):s.writeHead(404).end()); t.after(h.close); const directory = await stage(); await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:h.url,directory}),/partial/); });
test('maven rejects redirects, differing complete publications, and network failures', async t=>{const directory=await stage();const redirect=await fakeHttp((q,s)=>s.writeHead(302,{Location:'https://example.invalid'}).end());t.after(redirect.close);await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:redirect.url,directory}),/refused redirect/);const different=await fakeHttp((q,s)=>s.writeHead(200).end('wrong'));t.after(different.close);await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:different.url,directory}),/differs/);await assert.rejects(()=>mavenCreateOrCompare({repositoryUrl:'http://127.0.0.1:1',directory}),/request failed/);});
test('Maven staging is bound to the manifest coordinate, catalog digest, and regular files',async()=>{const fixture=await createReleaseFixture();const root=join(fixture.root,'maven');const version=join(root,'gg','grounds','resourcepacks-catalog','0.1.0');await mkdir(version,{recursive:true});await writeFile(join(version,'resourcepacks-catalog-0.1.0.jar'),fixture.files.get('grounds-resourcepacks-catalog-0.1.0.jar'));await writeFile(join(version,'resourcepacks-catalog-0.1.0.pom'),'<project/>');assert.equal((await collectMavenPublication({stagingDirectory:root,manifest:fixture.manifest})).length,2);await writeFile(join(version,'other.jar'),'x');await assert.rejects(()=>collectMavenPublication({stagingDirectory:root,manifest:fixture.manifest}),/outside the manifest coordinate/);});
