import assert from 'node:assert/strict'; import { createHash } from 'node:crypto'; import { mkdtemp, writeFile } from 'node:fs/promises'; import { join } from 'node:path'; import test from 'node:test';
import { fakeHttp } from './fake-http.mjs'; import { githubReleaseCreateOrCompare, releaseAssetsCreateOrCompare } from '../src/release-assets-create-or-compare.mjs';
import { createReleaseFixture } from './fixtures.mjs'; import { loadRelease } from '../src/manifest.mjs';
async function assets(){const d=await mkdtemp('/tmp/resourcepacks-task8/assets-');const n=['grounds-content-x.zip','grounds-platform-x.zip','grounds-resourcepacks-catalog-0.jar','manifest.json'];await Promise.all(n.map(x=>writeFile(join(d,x),x)));return n.map(name=>{const bytes=Buffer.from(name);return{name,file:join(d,name),size:bytes.length,sha1:createHash('sha1').update(bytes).digest('hex'),sha256:createHash('sha256').update(bytes).digest('hex')}});}
test('release assets uploads missing assets and skips equal existing assets',async t=>{const a=await assets();let uploaded=[];const h=await fakeHttp((q,s)=>s.end(q.url.slice(1)));t.after(h.close);await releaseAssetsCreateOrCompare({assets:a,existingAssets:[{name:a[0].name,url:`${h.url}/${a[0].name}`}],upload:x=>uploaded.push(x.name)});assert.deepEqual(uploaded,a.slice(1).map(x=>x.name));});
test('release assets reject a conflicting existing byte stream',async t=>{const a=await assets();const h=await fakeHttp((q,s)=>s.end('wrong'));t.after(h.close);await assert.rejects(()=>releaseAssetsCreateOrCompare({assets:a,existingAssets:[{name:a[0].name,url:h.url}],upload(){}}),/differs/);});
test('release assets reject unexpected and duplicate remote names before upload',async()=>{const a=await assets();await assert.rejects(()=>releaseAssetsCreateOrCompare({assets:a,existingAssets:[{name:'unexpected.zip',url:'https://example.invalid'}],upload(){}}),/unexpected or duplicate/);await assert.rejects(()=>releaseAssetsCreateOrCompare({assets:a,existingAssets:[{name:a[0].name,url:'https://example.invalid'},{name:a[0].name,url:'https://example.invalid'}],upload(){}}),/unexpected or duplicate/);});
test('GitHub rejects an attacker-controlled API origin before making a request',async()=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});let calls=0;await assert.rejects(()=>githubReleaseCreateOrCompare({release,apiBaseUrl:'https://attacker.example',token:'TOKEN_MARKER',fetchImpl:async()=>{calls+=1;throw new Error('must not call');}}),/API base URL is not trusted/);assert.equal(calls,0);});
test('GitHub rejects an untrusted upload URL returned by its API',async t=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});const http=await fakeHttp((request,response)=>request.url.includes('/releases/tags/')?response.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({id:7,upload_url:'https://evil.invalid/uploads{?name,label}'})):response.writeHead(200,{'Content-Type':'application/json'}).end('[]'));t.after(http.close);await assert.rejects(()=>githubReleaseCreateOrCompare({release,apiBaseUrl:http.url,token:'TOKEN_MARKER',allowLocalhostForTests:true}),/upload URL is unsafe/);});
