import assert from 'node:assert/strict'; import { join } from 'node:path'; import test from 'node:test';
import { fakeHttp } from './fake-http.mjs'; import { githubReleaseCreateOrCompare, releaseAssetsCreateOrCompare } from '../src/release-assets-create-or-compare.mjs';
import { createReleaseFixture } from './fixtures.mjs'; import { loadRelease } from '../src/manifest.mjs';
async function assets(){const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});return{fixture,release};}
test('release assets uploads missing assets and skips equal existing assets',async t=>{const {fixture,release}=await assets();t.after(()=>release.close());let uploaded=[];const h=await fakeHttp((q,s)=>{const asset=release.artifacts.find(value=>q.url===`/${value.name}`);s.end(fixture.files.get(asset.name));});t.after(h.close);await releaseAssetsCreateOrCompare({release,existingAssets:[{name:release.artifacts[0].name,url:`${h.url}/${release.artifacts[0].name}`}],upload:x=>uploaded.push(x.name)});assert.deepEqual(uploaded,release.artifacts.slice(1).map(x=>x.name));});
test('release assets reject a conflicting existing byte stream',async t=>{const {release}=await assets();t.after(()=>release.close());const h=await fakeHttp((q,s)=>s.end('wrong'));t.after(h.close);await assert.rejects(()=>releaseAssetsCreateOrCompare({release,existingAssets:[{name:release.artifacts[0].name,url:h.url}],upload(){}}),/differs/);});
test('release assets reject unexpected and duplicate remote names before upload',async()=>{const {release}=await assets();try{await assert.rejects(()=>releaseAssetsCreateOrCompare({release,existingAssets:[{name:'unexpected.zip',url:'https://example.invalid'}],upload(){}}),/unexpected or duplicate/);await assert.rejects(()=>releaseAssetsCreateOrCompare({release,existingAssets:[{name:release.artifacts[0].name,url:'https://example.invalid'},{name:release.artifacts[0].name,url:'https://example.invalid'}],upload(){}}),/unexpected or duplicate/);}finally{await release.close();}});
test('release assets rejects synthetic assets without a release before network or upload',async()=>{let uploads=0;let fetches=0;await assert.rejects(()=>releaseAssetsCreateOrCompare({assets:[{name:'evil'}],existingAssets:[],upload(){uploads+=1;},fetchImpl:async()=>{fetches+=1;return new Response();}}),/release artifact contract mismatch/);assert.equal(uploads,0);assert.equal(fetches,0);});
test('GitHub rejects an attacker-controlled API origin before making a request',async t=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});t.after(()=>release.close());let calls=0;await assert.rejects(()=>githubReleaseCreateOrCompare({release,apiBaseUrl:'https://attacker.example',token:'TOKEN_MARKER',fetchImpl:async()=>{calls+=1;throw new Error('must not call');}}),/API base URL is not trusted/);assert.equal(calls,0);});
test('GitHub Release assets fail closed for schema-v2 build publications',async()=>{const fixture=await createReleaseFixture({type:'build'});const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});let calls=0;await assert.rejects(()=>githubReleaseCreateOrCompare({release,token:'TOKEN_MARKER',fetchImpl:async()=>{calls+=1;throw new Error('must not call');}}),/require a release publication/);assert.equal(calls,0);await release.close();});
test('GitHub release and asset helpers reject mutated release artifact contracts before network or upload',async()=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});release.artifacts[0].contentType='text/plain';let calls=0;await assert.rejects(()=>githubReleaseCreateOrCompare({release,token:'TOKEN_MARKER',fetchImpl:async()=>{calls+=1;throw new Error('must not call');}}),/release artifact contract mismatch/);assert.equal(calls,0);let uploads=0;await assert.rejects(()=>releaseAssetsCreateOrCompare({release,existingAssets:[],upload(){uploads+=1;}}),/release artifact contract mismatch/);assert.equal(uploads,0);await release.close();});
test('GitHub rejects an untrusted upload URL returned by its API',async t=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});t.after(()=>release.close());const http=await fakeHttp((request,response)=>request.url.includes('/releases/tags/')?response.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({id:7,upload_url:'https://evil.invalid/uploads{?name,label}'})):response.writeHead(200,{'Content-Type':'application/json'}).end('[]'));t.after(http.close);await assert.rejects(()=>githubReleaseCreateOrCompare({release,apiBaseUrl:http.url,token:'TOKEN_MARKER',allowLocalhostForTests:true}),/upload URL is unsafe/);});
test('GitHub times out pending API headers without leaking credentials or handles',async()=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});const operation=githubReleaseCreateOrCompare({release,token:'TOKEN_MARKER',fetchImpl:()=>new Promise(()=>{}),timeoutMs:20});assert.equal(await Promise.race([assert.rejects(()=>operation,/GitHub request timed out/).then(()=> 'timeout'),new Promise(resolve=>setTimeout(()=>resolve('hung'),200))]),'timeout');await release.close();});
test('GitHub times out a stalled API response body',async()=>{const fixture=await createReleaseFixture();const release=await loadRelease({manifestFile:join(fixture.root,'manifest.json'),releaseDirectory:fixture.root});const body=new ReadableStream({start(){}});const operation=githubReleaseCreateOrCompare({release,token:'TOKEN_MARKER',fetchImpl:async()=>new Response(body,{status:200}),timeoutMs:20});assert.equal(await Promise.race([assert.rejects(()=>operation,/GitHub request timed out/).then(()=> 'timeout'),new Promise(resolve=>setTimeout(()=>resolve('hung'),200))]),'timeout');await release.close();});
